image: node:12.16

stages:
    - linting
    - build
    - publish

Linting:
    stage: linting
    script:
        - npm ci --ignore-scripts
        - npm run lint
    only:
        - merge_requests

Build:
    stage: build
    script:
        - npm ci --ignore-scripts
        - npm run build
    only:
        - master
    artifacts:
        paths:
            - dist/
            - node_modules/
        expire_in: 1 hours

Publish:
    stage: publish
    script:
        - echo "//registry.npmjs.org/:_authToken=$NPM_PUBLISH_KEY" > .npmrc
        # unsafe-perm is required as this pipeline runs as "root", which npm sees as unsafe
        - echo "unsafe-perm=true" >> .npmrc
        - npm version --no-git-tag-version --allow-same-version $(npm view @${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}@latest version)
        - npm version --no-git-tag-version patch
        - npm publish --verbose --access public
    tags:
        - build
    only:
        - master
